namespace AgentMesh.Application.Models
{
    /// <summary>
    /// Input model for saving an interaction to the agent's memory.
    /// </summary>
    public class AgentMemorySaverInput
    {
        /// <summary>
        /// The message provided by the user during the interaction.
        /// </summary>
        public string MessageByUser { get; set; } = string.Empty;

        /// <summary>
        /// The response generated by the assistant during the interaction.
        /// </summary>
        public string ResponseByAssistant { get; set; } = string.Empty;
    }
}
