namespace AgentMesh.Models.AgentMemory
{
    /// <summary>
    /// Input model for adding an interaction to the agent's memory. This class encapsulates the details of a single interaction between the user and the assistant, including the message provided by the user and the corresponding response generated by the assistant. It serves as a structured representation of an interaction that can be stored in the agent's memory for future reference and context-aware responses.
    /// </summary>
    public class AgentMemoryExecutorAddInteractionInput
    {
        /// <summary>
        /// MessageByUser represents the message or input provided by the user during an interaction with the agent. This property captures the user's query, command, or any form of communication that the agent needs to process and respond to. It serves as a crucial part of the interaction history, allowing the agent to understand and remember past interactions for better context and improved responses in future interactions.
        /// </summary>
        public string MessageByUser { get; set; } = string.Empty;

        /// <summary>
        /// ResponseByAssistant represents the response or output generated by the assistant during an interaction with the user. This property captures the assistant's reply to the user's query, command, or any form of communication. It serves as a crucial part of the interaction history, allowing the agent to provide contextually relevant and coherent responses based on past interactions.
        /// </summary>
        public string ResponseByAssistant { get; set; } = string.Empty;
    }
}
