<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Qdrant.Client" Version="1.18.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgentMesh.Application\AgentMesh.Application.csproj" />
    <ProjectReference Include="..\AgentMesh\AgentMesh.csproj" />
  </ItemGroup>

</Project>
