using AgentMesh.Models;

namespace AgentMesh.Services
{
    /// <summary>
    /// An agentic memory service that allows adding chat interactions to the agent's memory and querying the memory for relevant information based on a search query.
    /// This service enables the agent to retain context and information from previous interactions, allowing it to provide more informed and relevant responses in future interactions. 
    /// The memory can be used for various purposes, such as improving the agent's understanding of the user's preferences, maintaining a history of the conversation, or enabling the agent to learn from past interactions to enhance its performance over time.
    /// </summary>
    public interface IAgentMemoryService
    {
        /// <summary>
        /// Adds a chat interaction to the agent's memory, which includes the user's message and the agent's response.
        /// This allows the agent to retain context and information from previous interactions, enabling it to provide more informed and relevant responses in future interactions. 
        /// The memory can be used for various purposes, such as improving the agent's understanding of the user's preferences, maintaining a history of the conversation, or enabling the agent to learn from past interactions to enhance its performance over time.
        /// </summary>
        /// <param name="userId">The unique identifier of the user.</param>
        /// <param name="userMessage">The message sent by the user.</param>
        /// <param name="agentResponse">The response generated by the agent.</param>
        /// <param name="cancellationToken">A token to monitor for cancellation requests.</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        Task AddChatInteraction(string userId, string userMessage, string agentResponse, CancellationToken cancellationToken = default);

        /// <summary>
        /// Retrieves agent memory items matching the specified query for the given user.
        /// </summary>
        /// <param name="userId">The identifier of the user whose memory items are queried.</param>
        /// <param name="query">The search query used to filter memory items.</param>
        /// <param name="cancellationToken">A token to cancel the operation.</param>
        /// <returns>A task representing the asynchronous operation, containing a collection of matching agent memory items.</returns>
        Task<IEnumerable<AgentMemoryItem>> Query(string userId, string query, CancellationToken cancellationToken = default);
    }
}
