<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Application\**" />
    <Compile Remove="Models\RequirementsCollector\**" />
    <Compile Remove="Models\Router\**" />
    <EmbeddedResource Remove="Application\**" />
    <EmbeddedResource Remove="Models\RequirementsCollector\**" />
    <EmbeddedResource Remove="Models\Router\**" />
    <None Remove="Application\**" />
    <None Remove="Models\RequirementsCollector\**" />
    <None Remove="Models\Router\**" />
  </ItemGroup>

</Project>
