<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Router\**" />
    <EmbeddedResource Remove="Models\Router\**" />
    <None Remove="Models\Router\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\Configuration\" />
    <Folder Include="Models\RequirementsCollector\" />
  </ItemGroup>

</Project>
